# Dockerfile
### First Stage ###
FROM node:latest AS builder

WORKDIR /usr/src/app

COPY package.json package-lock.json ./

RUN npm install - force

COPY . .

ARG BASE_URL
ENV REACT_APP_BASE_URL=${BASE_URL}

RUN npm run build

### Second Stage ###
FROM caddy:2.1.1

ARG CADDYFILE
COPY ${CADDYFILE} /etc/caddy/Caddyfile

COPY --from=builder /usr/src/app/dist/ /srv

EXPOSE 80
EXPOSE 443

