FROM node:lts-alpine as builder-dev

ARG VITE_NODE_ENV
ARG VITE_FACEBOOK_APP_ID
ARG VITE_BASE_URL_SOCKET
ARG VITE_BASE_URL
ARG VITE_BASE_URL_LINK

ENV VITE_NODE_ENV=${VITE_NODE_ENV}
ENV VITE_FACEBOOK_APP_ID=${VITE_FACEBOOK_APP_ID}
ENV VITE_BASE_URL_SOCKET=${VITE_BASE_URL_SOCKET}
ENV VITE_BASE_URL=${VITE_BASE_URL}
ENV VITE_BASE_URL_LINK=${VITE_BASE_URL_LINK}

WORKDIR /app

COPY package*.json .

RUN npm i

COPY . .

RUN npm run build

COPY ./assets /app/dist/assets

FROM node:lts-alpine 

WORKDIR /app

COPY --from=builder-dev /app/dist/ /app/dist/

EXPOSE 3000

COPY package.json .
COPY vite.config.ts .

RUN npm install typescript

# EXPOSE 3000

# CMD [ "npm", "run", "preview" ]

FROM nginx

EXPOSE 3000

COPY ./nginx/default.conf /etc/nginx/conf.d/default.conf

COPY --from=builder-dev /app/dist /usr/share/nginx/html