# Use an official Node.js runtime as the base image
FROM node:latest as build-stage

# Set working directory
WORKDIR /usr/src/app

# Copy package.json and package-lock.json to the working directory
COPY package.json package-lock.json ./

# Install dependencies
RUN npm install - force

# Copy app source code to the working directory
COPY . .

# Build the app
RUN npm run build


# Expose port 80
EXPOSE 3000

ENV REACT_APP_BASE_URL=http://localhost:8000

CMD [ "npm", "run", "dev" ]


