version: '3.8'

services:
   react-app:
      image: adamb00/react-app
      restart: unless-stopped
      container_name: react-app
      build:
         context: ./client
         dockerfile: Dockerfile
      env_file:
         - ./client/.env.production
      volumes:
         - ./react-app:/app
      networks:
         - mern-app

   node-app:
      image: adamb00/api-server
      restart: unless-stopped
      container_name: api-server
      build:
         context: ./server
         dockerfile: Dockerfile
      env_file:
         - ./server/.env
      volumes:
         - ./node-app:/app/dist/
      networks:
         - mern-app

networks:
   mern-app:
      driver: bridge
