version: '3.8'

services:
   nginx:
      depends_on:
         - node-app
         - react-app
         - admin-app
      container_name: nginx
      restart: unless-stopped
      image: nginx
      ports:
         - 8080:80
         - 443:443
      volumes:
         - ./nginx/nginx.conf:/etc/nginx/nginx.conf
         - ./certbot/conf:/etc/letsencrypt
         - ./certbot/www:/var/www/certbot
         - ./client:/usr/share/nginx/r2byou.com
         - ./admin:/usr/share/nginx/admin.r2byou.com

   certbot:
      image: certbot/certbot
      container_name: certbot
      volumes:
         - ./certbot/conf:/etc/letsencrypt
         - ./certbot/www:/var/www/certbot
      command: certonly --webroot -w /var/www/certbot --force-renewal --email borsodi.dm@gmail.com -d r2byou.com -d www.r2byou.com --agree-tos

   admin-app:
      image: adamb00/r2byou:admin
      restart: always
      container_name: admin-app
      stdin_open: true
      tty: true
      networks:
         - mern-app

   react-app:
      image: adamb00/r2byou:frontend
      restart: always
      container_name: react-app
      stdin_open: true
      tty: true
      networks:
         - mern-app

   node-app:
      image: adamb00/r2byou:backend
      restart: always
      stdin_open: true
      tty: true
      container_name: api-server
      ports:
         - '8000:8000'
      env_file:
         - ./.env
      networks:
         - mern-app

networks:
   mern-app:
      driver: bridge
