version: '3.8'

services:
   react-app:
      image: adamb00/rr:client
      restart: unless-stopped
      container_name: react-app
      stdin_open: true
      tty: true
      ports:
         - '3000:3000'
      build:
         context: ./client
         dockerfile: Dockerfile
      networks:
         - mern-app

   node-app:
      image: adamb00/rr:server
      restart: unless-stopped
      container_name: api-server
      ports:
         - '8000:8000'
      build:
         context: ./server
         dockerfile: Dockerfile
      networks:
         - mern-app

networks:
   mern-app:
      driver: bridge
