version: '3.8'

services:
   react-app:
      image: adamb00/r2byou:react-app
      restart: unless-stopped
      container_name: react-app
      env_file:
         - client/.env.production
      ports:
         - '5173:5173'
      build:
         context: ./client
         dockerfile: Dockerfile
      # volumes:
      #    - ./react-app:/app
      networks:
         - mern-app

   node-app:
      image: adamb00/r2byou:api-server
      restart: unless-stopped
      container_name: api-server
      env_file:
         - server/.env
      build:
         context: ./server
         dockerfile: Dockerfile
      volumes:
         - ./node-app:/app/dist/
      networks:
         - mern-app

networks:
   mern-app:
      driver: bridge
