version: '3.8'

services:
   react-app:
      image: registry.digitalocean.com/rr-registry/frontend:latest
      restart: always
      container_name: react-app
      stdin_open: true
      tty: true
      ports:
         - '80:80'
         - '443:443'
      build:
         context: ./client
         dockerfile: Dockerfile
         args:
            - VITE_NODE_ENV=production
            - VITE_FACEBOOK_APP_ID=3092655644205329
            - VITE_BASE_URL_SOCKET=https://r2byou.com/
            - VITE_BASE_URL=https://r2byou.com/api/v1
            - VITE_BASE_URL_LINK=https://r2byou.com/
      networks:
         - mern-app
   node-app:
      image: registry.digitalocean.com/rr-registry/backend:latest
      restart: always
      stdin_open: true
      tty: true
      container_name: api-server
      ports:
         - '8000:8000'
      build:
         context: ./server
         dockerfile: Dockerfile
      networks:
         - mern-app

networks:
   mern-app:
      driver: bridge
