version: '3.8'

services:
   admin-app:
      image: adamb00/r2byou:admin
      restart: always
      container_name: admin
      stdin_open: true
      tty: true
      build:
         context: ./admin
         dockerfile: Dockerfile
         args:
            - VITE_NODE_ENV=production
            - VITE_FACEBOOK_APP_ID=3092655644205329
            - VITE_BASE_URL_SOCKET=https://r2byou.com/
            - VITE_BASE_URL=https://r2byou.com/api/v1
            - VITE_BASE_URL_LINK=https://r2byou.com/
      networks:
         - mern-app
   react-app:
      image: adamb00/r2byou:frontend
      restart: always
      container_name: frontend
      stdin_open: true
      tty: true
      build:
         context: ./client
         dockerfile: Dockerfile
         args:
            - VITE_NODE_ENV=production
            - VITE_FACEBOOK_APP_ID=3092655644205329
            - VITE_BASE_URL_SOCKET=https://r2byou.com/
            - VITE_BASE_URL=https://r2byou.com/api/v1
            - VITE_BASE_URL_LINK=https://r2byou.com/
      networks:
         - mern-app
   node-app:
      image: adamb00/r2byou:backend
      restart: always
      stdin_open: true
      tty: true
      container_name: backend
      ports:
         - '8000:8000'
      build:
         context: ./server
         dockerfile: Dockerfile
      networks:
         - mern-app

networks:
   mern-app:
      driver: bridge
