version: '3'

services:
   client:
      build:
         dockerfile: Dockerfile
         context: ./client
      container_name: client
      ports:
         - '5173:5173'
      stdin_open: true
      tty: true
      depends_on: [server]
      volumes:
         - ./client:/usr/src/app
         - /usr/src/app/node_modules
      networks:
         - mern-network

   server:
      build:
         dockerfile: Dockerfile
         context: ./server
      container_name: server
      restart: always
      ports:
         - '8000:8000'
      depends_on: [database]
      volumes:
         - ./server:/usr/src/app
         - /usr/src/app/node_modules

      networks:
         - mern-network

   database:
      image: mongo
      container_name: database
      ports:
         - '27017:27017'
      volumes:
         - ./data:/data/db
      networks:
         - mern-network

networks:
   mern-network:
      driver: bridge
