version: '3.8'

services:
   react-app:
      image: registry.digitalocean.com/rr-registry/frontend:latest
      restart: always
      container_name: react-app
      stdin_open: true
      tty: true
      ports:
         - '80:80'
         - '443:443'
      build:
         context: ./client
         dockerfile: Dockerfile
      env_file:
         - ./client/.env.production
      networks:
         - mern-app
   node-app:
      image: registry.digitalocean.com/rr-registry/backend:latest
      restart: always
      stdin_open: true
      tty: true
      container_name: api-server
      env_file:
         - ./server/.env
      ports:
         - '8000:8000'
      build:
         context: ./server
         dockerfile: Dockerfile
      networks:
         - mern-app

networks:
   mern-app:
      driver: bridge
