version: '3.8'

services:
   admin-app:
      image: adamb00/r2byou:admin
      restart: always
      container_name: admin-app
      stdin_open: true
      tty: true
      networks:
         - mern-app

   react-app:
      image: adamb00/r2byou:frontend
      restart: always
      container_name: react-app
      stdin_open: true
      tty: true
      networks:
         - mern-app

   node-app:
      image: adamb00/r2byou:backend
      restart: always
      stdin_open: true
      tty: true
      container_name: api-server
      ports:
         - '8000:8000'
      env_file:
         - ./.env
      networks:
         - mern-app

networks:
   mern-app:
      driver: bridge
