FROM node:lts-alpine as builder

WORKDIR /app/node-app

COPY package*.json ./

RUN npm ci

COPY . .

RUN npm run build

FROM node:lts-alpine

USER node

WORKDIR /app/node-app

COPY package*.json ./

RUN npm ci 

COPY --from=builder /app/node-app/dist/ /app/node-app/dist/

EXPOSE 8000

CMD [ "npm", "run", "start" ]