name: pipeline
on:
   push:
      branches:
         - 'main'

env:
   REGISTRY: 'adamb00'
   IMAGE_NAME: 'r2byou'

jobs:
   build_and_push:
      runs-on: ubuntu-latest
      steps:
         - name: Checkout repository
           uses: actions/checkout@v2

         - name: Login to Docker Hub
           uses: docker/login-action@v2
           with:
              username: ${{ secrets.DOCKERHUB_USERNAME }}
              password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

         - name: Set up Docker Buildx
           uses: docker/setup-buildx-action@v1

         - name: Build and push Docker images
           run: |
              docker-compose -f docker-compose.prod.yaml build
              docker-compose -f docker-compose.prod.yaml push

   deploy-to-digitalocean:
      runs-on: ubuntu-latest
      needs: build_and_push
      steps:
         - name: Checkout repository
           uses: actions/checkout@v2

         - name: SSH into DigitalOcean droplet and run docker-compose up
           uses: appleboy/ssh-action@master
           with:
              host: ${{ secrets.DROPLET_HOST }}
              username: ${{ secrets.DROPLET_USERNAME }}
              key: ${{ secrets.DROPLET_SSH_KEY }}
              port: ${{ secrets.DROPLET_SSH_PORT }}
              passphrase: ${{ secrets.SSH_PASSPHRASE }}
              script: |
                 echo "${{ secrets.DOCKERHUB_ACCESS_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

                  docker system prune -f

                  docker stop $(docker ps -q)
                  docker rm $(docker ps -a -q)

                  docker pull adamb00/r2byou:admin
                  docker pull adamb00/r2byou:frontend
                  docker pull adamb00/r2byou:backend

                  docker run -d --name admin adamb00/r2byou:admin
                  docker run -d --name frontend adamb00/r2byou:frontend
                  docker run -d --name backend -p 8000:8000 --env-file /root/.env adamb00/r2byou:backend

                  rm -rf /var/www/admin.r2byou.com
                  rm -rf /var/www/r2byou.com/html/assets

                  mkdir /var/www/admin.r2byou.com
                  mkdir /var/www/r2byou.com

                  docker cp admin:/var/www/admin.r2byou.com/html /var/www/admin.r2byou.com/html
                  docker cp frontend:/var/www/r2byou.com/html /var/www/r2byou.com/html
