name: pipeline
on:
   push:
      branches:
         - 'main'

env:
   REGISTRY: 'registry.digitalocean.com/rr-registry'
   IMAGE_NAME_FRONTEND: 'frontend:latest'
   IMAGE_NAME_BACKEND: 'backend:latest'

jobs:
   build-and-push:
      runs-on: ubuntu-latest
      steps:
         - name: Checkout the repo
           uses: actions/checkout@v2
         # - name: Create env file
         #   run: |
         #      touch .env
         #      echo "${{ secrets.SERVER_ENV_PROD }}" > .env
         #      cat .env

         - name: Remove previous images
           run: |
              docker compose -f docker-compose.yaml down
              docker rmi $(docker images -q) || true

         - name: Remove previous images from DO Container Registry
           run: |
              doctl registry repository delete $REGISTRY/$IMAGE_NAME_FRONTEND || true
              doctl registry repository delete $REGISTRY/$IMAGE_NAME_BACKEND || true

         - name: Build image
           run: docker compose -f docker-compose.yaml build

         - name: Install doctl
           uses: digitalocean/action-doctl@v2
           with:
              token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

         - name: Log in to DO Container Registry
           run: doctl registry login --expiry-seconds 600

         - name: Push image to DO Container Registry
           run: docker compose -f docker-compose.yaml push

   deploy-to-digitalocean:
      runs-on: ubuntu-latest
      needs: build-and-push
      steps:
         - name: Checkout repository
           uses: actions/checkout@v2

         - name: SSH into DigitalOcean droplet
           uses: appleboy/ssh-action@master
           with:
              host: ${{ secrets.DROPLET_HOST }}
              username: ${{ secrets.DROPLET_USERNAME }}
              key: ${{ secrets.DROPLET_SSH_KEY }}
              port: ${{ secrets.DROPLET_SSH_PORT }}
              passphrase: ${{ secrets.SSH_PASSPHRASE }}
              script: |
                 echo "${{ secrets.DOCKERHUB_ACCESS_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

                 docker stop $(docker ps -q)
                 docker rm $(docker ps -a -q)

                 docker pull registry.digitalocean.com/rr-registry/frontend:latest
                 docker pull registry.digitalocean.com/rr-registry/backend:latest

                 docker run -d --name frontend registry.digitalocean.com/rr-registry/frontend:latest
                 docker run -d --name backend -p 8000:8000 --ip --hostname --env-file /root/.env registry.digitalocean.com/rr-registry/backend:latest

                 docker cp frontend:/var/www/r2byou.com/html /var/www/r2byou.com
