name: node.js CI

on:
   push:
      branches: [master, main]

jobs:
   build:
      runs-on: self-hosted

      steps:
         - name: Checkout code
           uses: actions/checkout@v3

         - name: Install and Run
           working-directory: ./client
           run: |
              npm install

         - name: Install and Run
           working-directory: ./server
           run: |
              npm install
              export VERSION=$VERSION
              export PORT=$PORT
              export MONGO_DB=$MONGO_DB
              export MONGO_PASSWORD=$MONGO_PASSWORD

              export EMAIL_USERNAME=$EMAIL_USERNAME
              export EMAIL_PASSWORD=$EMAIL_PASSWORD
              export EMAIL_FROM=$EMAIL_FROM
              export EMAIL_HOST=$EMAIL_HOST
              export EMAIL_PORT=$EMAIL_PORT

              export JWT_SECRET=$JWT_SECRET
              export JWT_EXPIRES_IN=$JWT_EXPIRES_IN

              export AWS_BUCKET_NAME=$AWS_BUCKET_NAME
              export AWS_BUCKET_REGION=$AWS_BUCKET_REGION
              export AWS_ACCESS_KEY=$AWS_ACCESS_KEY
              export AWS_SECRET_KEY=$AWS_SECRET_KEY

         - name: Checkout code
           uses: actions/checkout@v3

         - name: Set up Docker Buildx
           uses: docker/setup-buildx-action@v1

         - name: Build and Push Docker image
           uses: docker/build-push-action@v2
           with:
              context: .
              file: ./docker-compose
              push: true
              registry: docker.io
              username: ${{ secrets.DOCKER_USERNAME }}
              password: ${{ secrets.DOCKER_PASSWORD }}
